### ISSUE TITLE
Remove the Obtain a UW NetID link from the idp login screen

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/uw-idp-custom#33]
Currently, the UW idP includes a link to obtain a UW NetID to an old resource. This link is creating problems for apps in the iOS store that use the UW idP as Apple believes this denotes creating an account. 
This issue is to remove the link as the service team has determined it is not needed on that page.

**Comment by kroberts-uw** [comment]
I would ask that the IAM team consider releasing this change as soon as realistically possible. 

The MyUW team cannot update the iOS app, because the app store review requires accounts that can be created in app to also be deleted in app. While we know this doesn't technically apply here, it still blocks any updates.

Because of increased complaints from students unable to install the app, and poor reviews in the app stores, the MyUW team made the decision today to remove the app from the store. The reputational damage for MyUW is significant and concerning.

At this point, many new users cannot install apps on iOS. Historically, almost 30% of MyUW usage is on iOS mobile devices. While many of those users already have the app installed, the urgency of updating the iOS app is growing. 

Thanks for considering.

**Comment by chmc3** [comment]
This was confirmed to be removed in https://github.com/UWIT-IAM/uw-idp-custom/pull/35
